# Generated by Django 3.0.7 on 2020-06-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20200604_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
