# Generated by Django 3.0.7 on 2020-06-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.URLField(max_length=255),
        ),
    ]
