# Generated by Django 3.0.7 on 2020-06-09 23:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_auto_20200609_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='embed_url',
            field=models.URLField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
