# Generated by Django 3.0.6 on 2020-05-24 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='post.Tag'),
        ),
    ]
