version: ‘3’
services:
 web:
 build: .
 command: bash -c “py manage.py makemigrations && py manage.py migrate && py manage.py runserver 0.0.0.0:8000”
 container_name: GreenEduLink
 volumes:
 — .:/GreenEduLink
 ports:
 — “8000:8000”